### ISSUE TITLE
Latest build does not work in PHP7

### ISSUE THREAD

**Issue by AniaSoft** [sasanrose/phpredmin#75] opened 2016-03-21 13:00 UTC
Hi, Please make it work with PHP7. Thank you!

**Comment by devdesco-ceo** [comment] 2016-03-21 20:39
Mine works just fine with latest PHP7

**Comment by drAlberT** [comment] 2016-05-27 14:16
mine too

**Comment by sasanrose** [comment] 2016-10-18 20:25
@AniaSoft Can you provide more information? Error messages or steps to reproduce this

**Comment by sasanrose** [comment] 2017-02-17 09:27
I'll close the issue since there were no more information provided

**Closed by sasanrose** 2017-02-17 09:27 UTC
